### ISSUE TITLE
Test on MX250 version

### ISSUE THREAD

**Issue by Yangff** [Cr0wTom/Mi-Notebook-Pro-Mods#11]
I just got my MI Notebook Pro with MX250 GPU. (aka. model 2019)

My bios version is `XMAKB5R0P0C07` 2/22/2019

I've tried to enable undervoltage and it worked out perfect. 
I also enabled SST and it seems at least my laptop didn't brick... But I've no idea if it works. 

Backup BIOS failed with Error 318: the host cpu does not have read access to the target flash area.

**Comment by bugiov** [comment]
thanks a lot for your sharing, I have ordered a version with mx250, I will try as soon as it arrives :) there are new versions of the bios for this machine?  Does your current version already have the fix for the fans and the keyboard backlight?

**Comment by Yangff** [comment]
The bios versions is not any listed in this repo and it's date is 2/22/2019. The fan works fine for me and there is a backlight option in the BIOS but I never tried it.

**Comment by bugiov** [comment]
ok thanks a lot, it's nice to know that there is compatibility for now with this new version ... as soon as mine arrives if it has the same Bios I will also try to do these mods

**Comment by Yangff** [comment]
[M00000000FFC00000.zip](https://github.com/Cr0wTom/Mi-Notebook-Pro-Mods/files/3342120/M00000000FFC00000.zip)
I dumped the bios from memory..

**Comment by bugiov** [comment]
hi, I finally received my mi notebook pro 2019 from banggood with considerable delay, and I am going to do the mods here ... confirm that yours is identical to the mx150 version?  with non-metallic fans like the gtx version?  no improvement? :(

**Comment by Yangff** [comment]
@buonincontrigi  Sorry, I only have MX250 version of mibook so I can't answer your question..

**Comment by bugiov** [comment]
> @buonincontrigi Sorry, I only have MX250 version of mibook so I can't answer your question..

I opened it, and I can tell you that inside is the new ssd samsung 970 evo, instead of the old 960, the fans are plastic (not those of the GTX variant), everything else seems ok, I don't know any difference visible.
For the patches that are here, I ran speedshift, bios unlock and voltage undervolt without any problems.

**Comment by yar-shukan** [comment]
just FYI XMAKB5R0P0906 bricks MX250 (2019 year version).

**Comment by aleqssss** [comment]
Same... I had the MX250 version with 0C07, now I have the MX250 version but it's bricked :/
I have tried to fix this with a ch341 to program the bios chip but nothing works (even the .zip file given in this thread)... I think we need a BIOS backup of 0C07 version and I don't have one.
If anybody have a backup maybe I could save about 1000 EUR ^^

**Comment by yar-shukan** [comment]
@Yangff could you please dump your BIOS as it's described in this repo readme? The .zip file that you've attached has file with size 4096 KB, and the valid size should be about 8192 KB.

You'd safe at least 2 losers here :)

**Comment by Yangff** [comment]
> @Yangff could you please dump your BIOS as it's described in this repo readme? The .zip file that you've attached has file with size 4096 KB, and the valid size should be about 8192 KB.
> 
> You'd safe at least 2 losers here :)

I'd like to help.. the problem is the backup script is not working..

```
Intel (R) Flash Programming Tool. Version:  11.6.29.3287
Copyright (c) 2007 - 2017, Intel Corporation. All rights reserved.

Reading HSFSTS register... Flash Descriptor: Valid

        --- Flash Devices Found ---
        W25Q64FV        ID:0xEF4017     Size: 8192KB (65536Kb)



Error 318: The host CPU does not have read access to the target flash area. To enable read access for this operation you must modify the descriptor settings to give host access to this region.
FPT Operation Failed.

Press any key to continue . . .
```
The `readEC.bat` works so I think there maybe some restriction on read the full bios from flash..
The 4mb image is what I read from memory with rw everything and I'm sure there is nothing left in the memory.. but I don't think you can flash it because it's different from the flash dump.. 

and I've secureboot disabled so it has nothing to do with that..

**Comment by Yangff** [comment]
By the way, unlocking the undervoltage should only change the NVRAM inside the SPI ROM, meaning that other parts of your SPI Flash should be intact. In theory, you should be able to dump the image and redo all the changes that the script made and re-flash it.. 

Also.. it's hard for me to understand why `0C07` also brick... if we're the same version it makes no sence for the differences... are you guys modifying EC? If so.. actually I can dump the EC region...

**Comment by yar-shukan** [comment]
@Yangff thanks mate for fast response. The workaround for this Error 318 is described here: https://github.com/Cr0wTom/Mi-Notebook-Pro-Mods#errors-and-fixes

If you can make it and publish backup - please send me your paypal so I could donate to you :)

**Comment by Yangff** [comment]
> @Yangff thanks mate for fast response. The workaround for this Error 318 is described here: https://github.com/Cr0wTom/Mi-Notebook-Pro-Mods#errors-and-fixes
> 
> If you can make it and publish backup - please send me your paypal so I could donate to you :)

cannot find a valid bios update to procedure this... 0906 is not compatible with MX250

Oh.. I don't need one.. let me try it.

**Comment by Yangff** [comment]
> @Yangff thanks mate for fast response. The workaround for this Error 318 is described here: https://github.com/Cr0wTom/Mi-Notebook-Pro-Mods#errors-and-fixes
> 
> If you can make it and publish backup - please send me your paypal so I could donate to you :)

[mybackup.zip](https://github.com/Cr0wTom/Mi-Notebook-Pro-Mods/files/3680236/mybackup.zip)

Good luck!

As a double check, my bios infos:
Product Name: TM1701
BIOS Version XMAKB5R0P0C07
EC Version XMAKB5R0P07

It took me some time because I don't know why but mibook's bios refuse to boot on NTFS U driver...

**Comment by yar-shukan** [comment]
@Yangff  thank you, it worked!  The only thing when I try to enter BIOS (restart -> F2) it asks for password.
Did you have any password set? If yes - could you please share it?

I think because of that the startup became slow - it's black screen for about 15-20 secs before MI screen is showed before Windows startup.

Anyway, thank you very much and if you could please share the last piece (BIOS password) - I'd very appreciate it.

Thank you in advance!

**Comment by aleqssss** [comment]
@Yangff 
Thank you so much !!! It is working, even when flashing with a CH341A.

After calculation I owe you about 240 beer (5 EUR = 50cl in France's bars) ^^

**Comment by yar-shukan** [comment]
@aleqssss could you please share your experience after this dump flash:
1. do you have extra 15-20 seconds on the boot before you see "MI" screen?
2. does it ask you for password when you try to enter BIOS (restart -> F2)?

@Yangff - if you had password and can share it - please, please, please :)

**Comment by aleqssss** [comment]
@yar-shukan 

Yep, I have the extra 20 sec and it is asking for password

**Comment by Yangff** [comment]
@yar-shukan @aleqssss password is `yangff`

**Comment by yar-shukan** [comment]
@Yangff  Thanks mate.

Password applied and reset BIOS settings but still have this strange delay from notebook turn on to first screen on startup  (like about 20 seconds PC does nothing).

I've talked to some hardware guy who works with this kind of stuff and problems: he explained it's because of "dirty ME region" because this dump comes from other PC. He said that it's possible to fix it, but by some reassembling of the dump and flushing it back.

Other option is probably to google for "how to fix bios me region problem" and give that a try, but I don't know how safe is that...

cc: @aleqssss

**Comment by yar-shukan** [comment]
Back to original business: is there any way to calm down fans kick off for version with MX250?

**Comment by Yangff** [comment]
> Back to original business: is there any way to calm down fans kick off for version with MX250?

I havn't tried but maybe you can patch your own fan control ec with BIOS Patcher? Just make sure to backup it before flashing...

**Comment by yar-shukan** [comment]
But I'm not totally sure available EC files are compatible with MX250 version and BIOS 0C07?
Any comments regarding this one @Cr0wTom ? Thank you

**Comment by Yangff** [comment]
> But I'm not totally sure available EC files are compatible with MX250 version and BIOS 0C07?
> Any comments regarding this one @Cr0wTom ? Thank you

I mean the pathcher inside the `BIOS Patcher` folder which should work by searching binary pattern and modifying the EC firmware... Usually this kind of patch should work especailly if the MX250's fan is as bad as MAX150's (or isn't it?) but you're on your own risk to do so because it may get off target. 

https://github.com/saltukkos/xiaomi-notebook-pro-bios-patcher/releases

As you can see the offset is "autodetect" by the patcher..

**Comment by Cr0wTom** [comment]
Hello guys, sorry but no time for the next month or so, I'm seeing that there is progress and this is good. If you manage to find a finilized way tell me to include it in my repo! :)

**Comment by Yangff** [comment]
Their is slight difference on pattern... I guess the offset should be `88189` on this ec.. However the datastruct looks like a little different so I won't try it..
you may modify that patcher if you want...

![Snipaste_2019-10-03_03-21-33](https://user-images.githubusercontent.com/1381921/66110750-02b3d480-e58d-11e9-8f8d-3cbdd9877080.png)
![Snipaste_2019-10-03_03-21-40](https://user-images.githubusercontent.com/1381921/66110751-02b3d480-e58d-11e9-96da-ffd653086dd9.png)

**Comment by aleqssss** [comment]
@yar-shukan I am trying to fix the 20sec bug, but I don't manage to clean the ME region... I don't really understand how it works.

**Comment by yar-shukan** [comment]
@aleqssss I've given notebook to one guy in my hometown and he's fixed that in couple of hours. There's some Intel tool and Distrib with ME regions for majority of vendors.
Probably try to find someone in your home town who can fix it for some $$.
Good luck

**Comment by BubiBalboa** [comment]
So, we simply can't update `XMAKB5R0P0C07`?

I'm glad the tool refused to patch the BIOS so I didn't have a brick on my hand but I'm still a lil sad there isn't a newer update available for this version of the laptop.

**Comment by Yangff** [comment]
> So, we simply can't update `XMAKB5R0P0C07`?
> 
> I'm glad the tool refused to patch the BIOS so I didn't have a brick on my hand but I'm still a lil sad there isn't a newer update available for this version of the laptop.

Unlocking overclock is fine on my side, I think they're trying to modify EC to get fan speed changed.. EC is not interchangable.

**Comment by dingspro** [comment]
Please heed my warning: I came here on research how to roll back the BIOS version, because I somehow naively applied BIOS "XMAKB5R0P0E07" from the official drivers section on mi.com, and now I get frequent memory related BSODs in Windows. I fired up mdsched.exe and it reports my memory is corrupted. Do not update from XMAKB5R0P0C07 to P0E07 on Mi Notebook Pro 2019 (TM1701-23949: i7-8550U / 16GB / MX250). I am currently digging through the files in this repository and https://composter.com.ua/documents/System_Tools_User_Guide_for_Intel_Management_Engine.pdf in the vague hope I can restore my system (which somehow still boots) to a working condition. I don't have any experience in BIOS hacking - I know this is a long shot because the latest reply here is a year old, but any help is appreciated. Is there any way I can (temporarily) limit my sys to use only first 4 or 8 gigs of memory, so I don't have to fear my corrupted memory access corrupts the bios flash? (BTW, People on reddit don't seem to be much help https://www.reddit.com/r/Xiaomi/comments/od0urk/frequent_windows_kernel_crashes_bsods_after/)

**Comment by okokokokokok94** [comment]
Does anyone have a clean xmakb5r0p0c07 bios dump?  The one that doesnt have 20 seconds boot time

**Comment by okokokokokok94** [comment]
> I just got my MI Notebook Pro with MX250 GPU. (aka. model 2019)
> 
> My bios version is `XMAKB5R0P0C07` 2/22/2019
> 
> I've tried to enable undervoltage and it worked out perfect. I also enabled SST and it seems at least my laptop didn't brick... But I've no idea if it works.
> 
> Backup BIOS failed with Error 318: the host cpu does not have read access to the target flash area.

hi may i know how you made a backup of your bios ?

**Comment by Yangff** [comment]
> > I just got my MI Notebook Pro with MX250 GPU. (aka. model 2019)
> > My bios version is `XMAKB5R0P0C07` 2/22/2019
> > I've tried to enable undervoltage and it worked out perfect. I also enabled SST and it seems at least my laptop didn't brick... But I've no idea if it works.
> > Backup BIOS failed with Error 318: the host cpu does not have read access to the target flash area.
> 
> hi may i know how you made a backup of your bios ?

Follow the `BIOS Update` section in readme until the `unlockme` step, you **don't** need to actually upgrade your bios. This `unlockme.nsh` will send certain EC command to unlock bios region to allow read and write certain region. 

I've no idea about the 20s thing, it seems caused by the Intel ME..

**Comment by Cr0wTom** [comment]
Closing the issue as the root issue is unrelated to this repo, and the follow-up discussion is discussed in another [issue](https://github.com/Cr0wTom/Mi-Notebook-Pro-Mods/issues/35)
