### ISSUE TITLE
[Enhancement] Bypass battery

### ISSUE THREAD

**Issue by scottinic** [Cr0wTom/Mi-Notebook-Pro-Mods#12]
What do you think about a battery charging treshold? Or simply a function to manually set the ec to set the laptop in "plugged in but not charging" mode.

Personally I keep my machine plugged in all day long and from time to time I need to be able to carry it with me for an hour or so, causing the battery to discharge to about 80% and consequently charge back to 100% a couple times a day every day.

**Comment by bugiov** [comment]
Hi, news?

**Comment by john-mad-biker** [comment]
+1 for this. It's very useful feature for minimize battery wear. If you don't need to have battery fully charged (in other words, if you don't care about max 'on battery' working time), it'll be good to have an oportunity to enable mode when charging stops at, let's say, 67 or 80 percents from max.

**Comment by octisfall** [comment]
+1

**Comment by Cr0wTom** [comment]
Closing this issue as the project is dead (the laptop is sold). 

In case someone wants to implement the function, make a pull request and I will try to merge it :)
