### ISSUE TITLE
bios 906 battery life?

### ISSUE THREAD

**Issue by artemis77799** [Cr0wTom/Mi-Notebook-Pro-Mods#16]
Hi, I'm currently on BIOS 805 and fans are really anooying, they start spinning even when I am doing nothing. I'd like to upgrade to bios 906 since it has quiter fans but I red some comments saying that battery sucks on that bios... I don't know what to do so I'm trying to get some feedback about bios 906 battery life

**Comment by Cr0wTom** [comment]
Issue unrelated with the context of the repo. Closing the issue
