### ISSUE TITLE
0906 bios slow SSD speed

### ISSUE THREAD

**Issue by jackreeves** [Cr0wTom/Mi-Notebook-Pro-Mods#2]
Firstly, Great work on collecting these together. However, After installing 0906 on pm961 on my Notebook Pro I get slow speeds. 2k read 1k write. Anyone else encounter same issue? Possible solutions?

**Comment by Cr0wTom** [comment]
Is it alright now? I have heard from another guy the same issue but most of the people that installed the bios are ok with the speeds (3k write etc)!

**Comment by jackreeves** [comment]
Yeah I updated all drivers from Xiaomi and switched to crystal to measure. Which I'd been more scientific but crystal showed 3k+ after. Thanks for all the great work!
