### ISSUE TITLE
Which BIOS would you recommend?

### ISSUE THREAD

**Issue by clmsftsw** [Cr0wTom/Mi-Notebook-Pro-Mods#21]
What is the best BIOS you can use for the Mi Pro right now?
I've seen that you would not recommend using the 906. (you wrote that at #4)
I am currently using the  502. Is there a point of updating it?

Thank you!

**Comment by Cr0wTom** [comment]
I am currently using the XMAKB5R0P0603 because of the issues mentioned for the 906 BIOS. You can test them and see what suits you best as I do not remember the changes from 502 to 603
