### ISSUE TITLE
.\bios_unlock.cmd Fail

### ISSUE THREAD

**Issue by ArduinoBen** [Cr0wTom/Mi-Notebook-Pro-Mods#22]
I've been trying to get the fan tweak working on my first gen i7/16G Mi Notebook Pro on BIOS version XMAKB5R0P0603.  I am able to backup my bios firmware using .\backup.cmd, but .\bios_unlock.cmd or .\bios_lock.cmd gives me the following error:

Xiaomi Mi Notebook Pro BIOS write lock patch by _Cyb_
Tested on 0603 BIOS
Now parsing Variable Information.
LoadDeviceDriver fail, GetLastError = 0x2
Failed to get bios data!
Fail to get Variable Information.
Failed to read variables!

Am I doing anything wrong?  How can I solve this problem.

**Comment by Cr0wTom** [comment]
Do you run the script in a CMD (or powershell) with admin rights ?

**Comment by ArduinoBen** [comment]
Yes, Powershell window opened in the Patches folder.

**Comment by ArduinoBen** [comment]
Also, I opened Powershell by shift+RMB on the folder, then clicked yes when the cmd.exe window popped up and asked for admin rights.  Do I also need to start PowerShell with admin rights?

**Comment by ArduinoBen** [comment]
Update: Still get the issue when running PowerShell as an admin, I'll try to figure it out.

**Comment by Cr0wTom** [comment]
Your BIOS is supported so I do not see a reason for it to not work. 

Try to run CMD with admin rights and not Powershell, and tell me what happens.

**Comment by ArduinoBen** [comment]
It still doesn't work :(

![Capture](https://user-images.githubusercontent.com/35127321/74035376-1f599080-49f5-11ea-8096-fef6285776f4.PNG)

**Comment by ArduinoBen** [comment]
Anyone have a solution?

**Comment by kanekifont** [comment]
@ArduinoBen i have the same problem, have you found a solution?

**Comment by ArduinoBen** [comment]
Haven't found a solution, but I've yet to try the patch Cr0wTom just released.

**Comment by kanekifont** [comment]
i have the solution after 30 min of try... you have to disable windows defender.....

**Comment by ArduinoBen** [comment]
Ahhhh, I've been trying to disable it for ages but it keeps coming back. I bet it's deleting parts of the package as it always does... Thanks bud 🙂🙂🙂

**Comment by kanekifont** [comment]
You are welcome, but i still have a problem. i run the undervolt script but i cant install the xtu intel software.

**Comment by ArduinoBen** [comment]
@kanekifont I've had this issue before!  For some reason, the later versions of XTU seems to not want to run on laptops.  I had to pull a copy I downloaded in 2018 from my backups to get it to run.  If you still have this problem I can try to find it and send it to you.

**Comment by ArduinoBen** [comment]
Figured it out guys!  None of the mods were working before.  Turns out Windows Defender real time protection is a real bitch and after disabling it everything worked perfectly!  Just remember that you need to disable it after every restart if you don't want it to delete your files - keep the zip file just to be safe.

Thanks Cr0wTom for making these mods!

**Comment by tsepa0** [comment]
I solved issue that youve been discussing about, but now, i have that error message:
Xiaomi Mi Notebook Pro BIOS write lock patch by _Cyb_
Tested on 0603 BIOS
Now parsing Variable Information.
Succeed to get bios data.
Complete parsing Variable Information!!!

Saving Variable Information to file: pchsetup_my.txt
Successfully read variables
./patchscript_bue : File C:\Users\stepan\Desktop\Mi Notebook Pro patches\bin\patchscript_bue.ps1 cannot be loaded. The
file C:\Users\stepan\Desktop\Mi Notebook Pro patches\bin\patchscript_bue.ps1 is not digitally signed. You cannot run
this script on the current system. For more information about running scripts and setting execution policy, see
about_Execution_Policies at https:/go.microsoft.com/fwlink/?LinkID=135170.
At line:1 char:1
+ ./patchscript_bue
+ ~~~~~~~~~~~~~~~~~
    + CategoryInfo          : SecurityError: (:) [], PSSecurityException
    + FullyQualifiedErrorId : UnauthorizedAccess
![79637063-b9238380-8184-11ea-8a9c-7998925b56d7](https://user-images.githubusercontent.com/17403388/79637070-c9d3f980-8184-11ea-9997-bed786e15ccf.png)

**Comment by Cr0wTom** [comment]
Closing the issue as it got resolved.

**Comment by potatosalad775** [comment]
For those who are looking for way to solve this problem - 

If you are using latest Win 11, you also have to disable features under 'Core Isolation' in Windows Defender.
simply disable all those features, reboot, and try again.

**Comment by Y4r0z** [comment]
Still have same issue (Windows defender disabled and other stuff disabled)
