### ISSUE TITLE
Mi notebook pro i7 MX150 charging issue on 906

### ISSUE THREAD

**Issue by aureh12** [Cr0wTom/Mi-Notebook-Pro-Mods#23]
Hi guys,
I really need your help with this.
I upgraded the BIOS to 960 and it makes my computer finally quiet (fan noise).
The problem now is that it only charges with power cord when in OFF or HIBERNATE or SLEEP states.
As soon as Windows 10 starts the charging LED blinks and Windows says it is plugged (but it doesn't charge). The blinking LED seems to indicate that it tries to charge then stop then charge then stop.
I uninstall the battery devices several times, but no luck.
Do you have any idea how to solve this ?

**Comment by Cr0wTom** [comment]
Did you try to reset BIOS settings, and clear CMOS?

**Comment by aureh12** [comment]
I did reset BIOS setting to default.
I didn't clear CMOS. How do you suggest me to clear CMOS?

**Comment by aureh12** [comment]
Problem solved after reinstalling Windows 10
