### ISSUE TITLE
Patch Error Bios 0603

### ISSUE THREAD

**Issue by kanekifont** [Cr0wTom/Mi-Notebook-Pro-Mods#24]
Xiaomi Mi Notebook Pro BIOS write lock patch by _Cyb_
Tested on 0603 BIOS
Now parsing Variable Information.
LoadDeviceDriver fail, GetLastError = 0x2
Failed to get bios data!
Fail to get Variable Information.
Failed to read variables!

**Comment by Cr0wTom** [comment]
https://github.com/Cr0wTom/Mi-Notebook-Pro-Mods/issues/22 

Please refer to this issue, you can discuss it with the guy that has the same issue.
