### ISSUE TITLE
200 to 906 didn't fix SSD Speeds

### ISSUE THREAD

**Issue by Sylphe** [Cr0wTom/Mi-Notebook-Pro-Mods#25]
I have recently upgraded the BIos from the 200 original version to the latest 906.
While the fans are more silent, the SSD speeds are still the same as before.
I have updated all drivers with SDRI , tried a clean install with Xiaomi only drivers, tried all power options, but nothing has been working. 
Everything shows that the PCIe should be performing at 4X.

I see that @jackreeves had a similar issue here : https://github.com/Cr0wTom/Mi-Notebook-Pro-Mods/issues/2  but his solution of reinstalling did not work for me 

![hwinfo](https://user-images.githubusercontent.com/9304246/78470619-439ec880-772b-11ea-9088-04ac415f621f.PNG)
![hwinfo2](https://user-images.githubusercontent.com/9304246/78470620-44cff580-772b-11ea-8f1e-19d9e0d127cd.PNG)
![crystal](https://user-images.githubusercontent.com/9304246/78470621-44cff580-772b-11ea-8e44-2bbadfff2d98.PNG)
![crystalmark](https://user-images.githubusercontent.com/9304246/78470623-45688c00-772b-11ea-94f8-fff09b8b5056.PNG)

**Comment by Cr0wTom** [comment]
Try downgrading to a lower version like the 3XX one! And step it up one version at a time! In general 906 is not suggested by me because it results in lower battery performance.

**Comment by Sylphe** [comment]
For the downgrade, do you think it is safe to do it ? The 906 update was simple since there was no messing with bootable usb keys. Do I just need to edit the platform.ini like in the instructions ?

I can;t really tell about the battery performance for the 906 since my battery wear is at 30% now so it's quite bad in general, but I haven't really noticed it being any noticeably worse than on the 200

**Comment by Cr0wTom** [comment]
If you do it correctly I don't think that it will be any issue at all! But, you are doing it by your own and it's your responsibility if anything happens to it! 

About the keys, if you have an encrypted drive keep the decryption keys, as if the boot keys are randomised again you will be able to decrypt the drive and use it with the new keys :)

**Comment by Sylphe** [comment]
OK I don't have encrypted drives fortunately.
I will consider dowgrading to 300, which had the SSD fix, then probably back to 906

**Comment by Cr0wTom** [comment]
No don't go back to 906 , try the 6XX one first, it may suit you best! You can apply the fan patch and the only thing missing will be the keyboard constant lighting but you may live with it!

**Comment by Sylphe** [comment]
I downgraded to the 300 bios . It fixed the SSD Issue and speeds are comparable to the ones posted after the fix (see pic).
![crystalmark300bios](https://user-images.githubusercontent.com/9304246/78499799-09492180-7753-11ea-976c-621ea47d76ad.PNG)

I have currently upgraded back to 603 bios and just ran another test. The speeds have dropped quite a lot on the sequential read.
![crystalmark603bios](https://user-images.githubusercontent.com/9304246/78501346-a314cc80-775b-11ea-8674-2d53363ceae3.PNG)

**Comment by Cr0wTom** [comment]
This is not a huge drop and it can be of the situation, but the strange thing is the write speed which is still really low! I don't really know what happens, try to reset your BIOS again and clear CMOS!

**Comment by Sylphe** [comment]
What do you mean by reset Bios ? Go back down to 300 and back up ? By clear CMOS you mean default settings in Bios or opening it and removing the battery ?

**Comment by Sylphe** [comment]
I changed SSD to a 1Tb Sabrent Rocket Q with speeds of 3.4KRead/2KWrite. 
I'm getting good speeds on it as advertised on the reading part, which indicates that the solution of going from 906>300>603 fixes the 2X PCIe issue( the slower write speed must be dependant on the perfomance of the Laptop)
![SabrentRocketQ1Tb](https://user-images.githubusercontent.com/9304246/79650001-42e94600-81b1-11ea-8642-500abc8b8eef.PNG)

I guess the speeds on the original samsung on the 300bios of 3.2K read must be overstated since the SSD is supposed to only be 2.8KRead/1.1KWrite , which is more in line with the readings I had on the 603 Bios.
