### ISSUE TITLE
Possible to enable pcie lanes on WWAN/LTE card slot?

### ISSUE THREAD

**Issue by summershrimp** [Cr0wTom/Mi-Notebook-Pro-Mods#27]
The WWan card slot have one pcie lanes to pch, with no capacitors and connectors solidered. 
After solidered the connectors and capacitors, USB channel is working but pcie seems currently disabled.

**Comment by great9** [comment]
can you provide more details, photos?

**Comment by MarFre22** [comment]
Hi @summershrimp ,
For now, we can solder 2 connectors (USB channel) in order to enable Bluetooth from PCIe Wi-Fi board (with M.2 adapter), for example. This has been used in hackintosh.

**Comment by Cr0wTom** [comment]
The issue has been discussed in the hackintosh section :) Closing the issue
