### ISSUE TITLE
Error 318 and 906

### ISSUE THREAD

**Issue by scottinic** [Cr0wTom/Mi-Notebook-Pro-Mods#3]
Even after following the troubleshooting section, it is not possible to execute the backup script.
I'm on bios 906 (laptop has been shipped with it), haven't tried any other script.

Also, in case of hardbrick, will the insydeh2o usb rescue procedure work (https://www.bios-mods.com/bios-recovery/insyde-bios-recovery/)?

**Comment by Cr0wTom** [comment]
If it is shipped with this BIOS it is a relatively new machine Wich means
that the scripts may not work! Also for a hardbrick I do not really know
what you can do! A hardbrick is always a shity situation! :/

**Comment by lowlevl** [comment]
@Cr0wTom , I think you don't wanna leave those informations in the wild !!!
