### ISSUE TITLE
Reset the bios password

### ISSUE THREAD

**Issue by atsen-dev** [Cr0wTom/Mi-Notebook-Pro-Mods#35]
HI, like another issue in this repo, I have problem to reset my BIOS password.
I've locked because I have made a mistake in my password and I'm not able to reset my bios password

This issue is related to [this](https://github.com/Cr0wTom/Mi-Notebook-Pro-Mods/issues/6) issue.

I've answered in this issue but unfortunately no response.

Someone hae an idea to complete the solution proposed in previous issue ?

Thank in advance

**Comment by LukasLohmar** [comment]
i had the same problem where i had an additional character which cannot be written with the US-keyboard at the end of my password after updating to the newest bios. u can just downgrade to the XMAKB5R0P0906 version and set the following flags inside platform.ini before you start the flashing utility

[Bios_Version_Check]
Flag=0

[ForceFlash]
Password=1

it is mentioned inside this section under Downgrade: https://github.com/Cr0wTom/Mi-Notebook-Pro-Mods#bios-update

EDIT: password will be 1234 after the password reset

**Comment by atsen-dev** [comment]
Hi, I'm testing your solution and it does not work wit ha mi notebook pro (mx250 version), when I run utility I have an error : 
![image](https://user-images.githubusercontent.com/32575538/147853625-257063ff-4765-43f5-9388-bdc3d6829fb0.png)

Can anyone help me ? 

Thank in advance

Edit : my platform.ini file content : 
...
[Bios_Version_Check]
Flag=0 
....

**Comment by atsen-dev** [comment]
@Cr0wTom did you ever had this problem ? Or anyone else ?

**Comment by LukasLohmar** [comment]
so, i looked into it and i think the problem is that for the mx-250 they use a different BIOS

the mx-250 version is for example: XMAKB5R0P0C07, but in this repo you can only find the XMAKB5R0P0A07, since its a different version.

you need to find a working backup for the mx-250 version. i searched for a bit but couldnt find one. my idea would be to go to this site: https://www-mi-com.translate.goog/service/bijiben/drivers?_x_tr_sl=zh-CN&_x_tr_tl=en&_x_tr_hl=en&_x_tr_pto=sc and enter your serialnumber, then scroll to the last section where they provide the BIOS download and try to change the download url to the version you want (actually dont know if it works).

**Comment by atsen-dev** [comment]
Ok, thanks. 

I'm always looking for that but not positive result about that.
I'll continue to search and update this issue when found.

Thank

**Comment by heyiamsven** [comment]
**_Disclaimer: I'm not responsible for any consequences of this guide. Use it only as reference. Make sure to ALIGN every PIN correctly (this includes everything on the CHA341a programmer and at your BIOS Chip), MAKE SURE the Voltage fits your BIOS chip. Wrong usage of the CHA341a programmer can destroy/damage your BIOS chip!_**

If nothing helps for you:
1. Buy a cheap CHA341a Programmer from AliExpress - make sure you get all adapters+probe with it
2. Locate the BIOS chip on the motherboard
3. Check on the internet (input chip number) what Voltage the BIOS chip runs (BIOS chip has 8 legs and a chip number on it)
4. Optional: If your BIOS Chip runs at 1.8V, you have to plug the 1.8V adapter from the CHA341a kit correctly ontop of the CHA341 device (make sure that all pins align correctly)
5. Disconnect Battery (and CMOS battery; if you have one)
6. Connect CHA341a probe to the BIOS chip (make sure that you connected the pins from the probe correctly to the BIOS chip pins - there should be a dot on one corner of the chip - this means it's PIN 1 -> Red cable from the probe should go on PIN 1 = correct connection)
7. Use CHA341a programmer software to read/dump BIOS and save it on your computer. If everything is fine the file should be 16MB/8MB (depending on your used BIOS chip)
8. Use UEFIExtract on the dumped BIOS bin file
9. Use UEFITool on the extracted BIOS bin file
10. Ctrl+f -> "Text Search" -> "Supervisor"
11. You will see all results from the search in the bottom window, one of the results contains the BIOS password (unencrypted)
12. Right click on each -> Hex View -> Scroll through everything; skip the gibberish until some text on the right side apears, seperated by dots. You will find sth like: S.u.p.e.r.v.i.s.o.r.P.W.. do that for each found search result until you got the PW.

Hope this helps you, I had the exact same issue and nothing helped (tested everything that was listed on this git), even the trick with plattform.ini and reflashing, I was able to reflash the same BIOS but this didn't removed the password somehow as recommended here. Just FYI I did it on a RedmiBook 16.

So I purchased this CHA341a programmer and did everything as stated above, now I'm finally able to get into my BIOS again :)
Pretty sure this works for all Xiaomi Notebooks.

**Comment by Cr0wTom** [comment]
I guess the solution is clear from now on :) Thank you all

**Comment by tcheip** [comment]
Dear @heyiamsven 

Thank you for the technique, I'm running with a system in BIOS legacy and not UEFI (i've check it using https://www.fosstechi.com/check-linux-system-uses-uefi-or-bios/).

Do you think your technique could work with a BIOS legacy system ?

Thank you

**Comment by heyiamsven** [comment]
Dumping/Flashing BIOS Chips with the correct programmer will always work as
long as the Chip is working properly. However reading out or modifying the
password from a BIOS dump heavily depends on the technique that is used by
the OEM to store the password on the chip.

If you know someone that has the same mainboard (donor board) and a
programmer you could theoretically dump the BIOS from the donor board and
flash it to your board.

As already mentioned, you could theoretically cause damage to your hardware
if you don't know what you are doing.

tcheip ***@***.***> schrieb am Do., 26. Dez. 2024, 17:26:

**Comment by tcheip** [comment]
Thank you very much for answering @heyiamsven 

My laptop is a Xiaomi notebook 15.6 and the BIOS chip is an Insyde brand.
I ordered a magnifying glass to be able to read the model written on it.
In the place I live I don't have access to a programmer technician, therefore I'll try to myself to read the BIOS and find my forgotten password.

I was wondering if steps 8 and 9 will work with a non UEFI system as it mention UEFI extract and UEFI tool. But I guess I'll get a 100% answer when I'll try it.
If i'm not successfull with this technique i've seen some sellers on ebay that sell pre programmed chips to replace mine, they just ask to get all the hardware information to program the chip.

I'll share my progress on the thread for anyone that may have the same problem.

**Comment by heyiamsven** [comment]
Then it will work. But I doubt you will find a pre programmed chip with the
correct BIOS FW for your laptop model as Xiaomi laptops aren't popular
enough (with CN and RU as exception).

Just to make it clear: A flash chip with the same SN doesn't contain
automatically the right FW for your device.

tcheip ***@***.***> schrieb am Fr., 27. Dez. 2024, 14:20:

**Comment by tcheip** [comment]
It works fine thanks a lot for your assistance @heyiamsven .

I'd like to share some more details for this procedure on xiaomi notebook pro 15.6 model TM1701: 

- Make sure the CHA341a Programmer yellow pin is placed on the two first pins.
- Install the CHA341a Programmer driver.
- Ensure the CHA341a Programmer locker is properly closed on the pins otherwise you'll just get FF as data in your file (if you have only FF it means the CHA341a Programmer did not read the chip).
- I was not able to find the text S.u.p.e....  using the ctrl f shortuct even selecting the text option search. If you are having the same issue you can search for the following hexa code to find the password line : 00 65 00 72 00 76 00 69 00 73 00 6F 00 72 00 50.
