### ISSUE TITLE
How to enable vt-x?

### ISSUE THREAD

**Issue by crutch12** [Cr0wTom/Mi-Notebook-Pro-Mods#38]
There is no setting in UEFI BIOS menu.

And it's disabled by default:
![image](https://user-images.githubusercontent.com/19373212/167624267-b566f708-94ed-4dab-9372-10a656de55d7.png)

**Comment by Pakophan** [comment]
Please let me know if you find a solution.

**Comment by crutch12** [comment]
@Pakophan
1) enable secure boot (bios)
2) disable hyper-v: run `bcdedit /set hypervisorlaunchtype off` (reason: https://github.com/microsoft/WSL/issues/5030)

Now it works (but I enabled hyper-v back, I need wsl and docker)
