### ISSUE TITLE
Bios xmakb5r0p0a07

### ISSUE THREAD

**Issue by ProtoThis** [Cr0wTom/Mi-Notebook-Pro-Mods#4]
Hi, not really an issue but I received my i7 mx150 16gb Xiaomi mi notebook pro about a week ago.

It appears mine is running bios xmakb5r0p0a07 which seems like a newer version. Before I flash 906 (downgrading) with better fan curve is there anything you need or is there a way to backup / upload the bios. Would be great to also have this version supported.

With kind regards

Ferry

**Comment by Cr0wTom** [comment]
Wow, its first time that I see this BIOS so please do not downgrade it. And
some points:

- Some users cannot downgrade from the shipped version so be aware.
- the 906 fixes the fan curve but generally it affects performance and
battery life by much so I wouldn't suggest it for now.

I will search for how you can backup your bios and I will tell you if you
can help me in the next couple of days. Thank you :)

**Comment by ProtoThis** [comment]
Great will refrain from downgrading then :-). Don't have a lot of time but would be great if at least I could backup and upload the bios somewhere so others can have a play with it (very curious on what the update contains :-).

**Comment by danilocbueno** [comment]
@Cr0wTom, if you know, did you realize any diff about this version? I am with the 906 and still have some issues with fan curve, the notebook is getting hotter etc..

**Comment by Cr0wTom** [comment]
> @Cr0wTom, if you know, did you realize any diff about this version? I am with the 906 and still have some issues with fan curve, the notebook is getting hotter etc..

Hey @danilocbueno , I didn't realize any differences... It's probably minor issues that were fixed :)

**Comment by danilocbueno** [comment]
thxs @Cr0wTom for the answer!!

I will try to update over the weekend and then I share here with you!
