### ISSUE TITLE
Reset the bios password

### ISSUE THREAD

**Issue by alkanna** [Cr0wTom/Mi-Notebook-Pro-Mods#6]
I've tried everything I could think of, disconnecting the battery for a month did not fix it, flashing the bios with force flash flags set to 1 (to reset password setting), downgrading it...
I even tried dumping the bios to see if I could find anything useful related to the password, it's a no go.
I think I mistakenly set a blank pass, because I always set the same bios pass when I do.

Do you think there is any way to mod the bios file to re flash it and get rid of the stored settings ?

**Comment by Cr0wTom** [comment]
The proper way to restore the bios settings (with the password) is to
unplug the battery (as there is no cmos battery on the board). Try also
with the battery unplugged to press the power button for at least 20
seconds , leave it for a minute and then re-plug the battery! I think that
it will do the trick :)

Thomas Sermpinis (a.k.a. Cr0wTom)

Cell: +30 6978089151
Email: serbinistom007@gmail.com
http://cr0wsplace.wordpress.com
(Sent from an android)

**Comment by royalidea** [comment]
Did you find a solution?

**Comment by derbestedaniel** [comment]
> I've tried everything I could think of, disconnecting the battery for a month did not fix it, flashing the bios with force flash flags set to 1 (to reset password setting), downgrading it...
> I even tried dumping the bios to see if I could find anything useful related to the password, it's a no go.
> I think I mistakenly set a blank pass, because I always set the same bios pass when I do.
> 
> Do you think there is any way to mod the bios file to re flash it and get rid of the stored settings ?

Did you find a solution? I find myself also confronted with being locked out of my bios :/
Tried disconnecting the battery... didn't work. 
(Mi Air 13.3; also no cmos battery)
Thanks in advance.

**Comment by royalidea** [comment]
> > I've tried everything I could think of, disconnecting the battery for a month did not fix it, flashing the bios with force flash flags set to 1 (to reset password setting), downgrading it...
> > I even tried dumping the bios to see if I could find anything useful related to the password, it's a no go.
> > I think I mistakenly set a blank pass, because I always set the same bios pass when I do.
> > Do you think there is any way to mod the bios file to re flash it and get rid of the stored settings ?
> 
> Did you find a solution? I find myself also confronted with being locked out of my bios :/
> Tried disconnecting the battery... didn't work.
> (Mi Air 13.3; also no cmos battery)
> Thanks in advance.

No never found a solution.

**Comment by atsen-dev** [comment]
any update about that ?

**Comment by okokokokokok94** [comment]
same problem but no clear solution . some people know how to find the password in .bin file of bios backup but they dont want to share the instruction selfish people. 
from what is research this is how they do it.
1. they backup their bios. but i dont know what tool to use and how to backup bios.
2.  from the backup bin file they use hex editor or some programs i dont know what program it is. to search for some text or words in the file like (supervisor password or master password). 
3. next to that text they will see the original password. 
4. but sad they dont want to tell how they do it

**Comment by atsen-dev** [comment]
> same problem but no clear solution . some people know how to find the password in .bin file of bios backup but they dont want to share the instruction selfish people. 
> from what is research this is how they do it.
> 1. they backup their bios. but i dont know what tool to use and how to backup bios.
> 2.  from the backup bin file they use hex editor or some programs i dont know what program it is. to search for some text or words in the file like (supervisor password or master password). 
> 3. next to that text they will see the original password. 
> 4. but sad they dont want to tell how they do it


Do you know why they doesn't want ?
They doesn't also in a conversation not public ?
Can you tell me if you have a solution for that problem, I will do the same.

**Comment by okokokokokok94** [comment]
> Do you know why they doesn't want ? They doesn't also in a conversation not public ? Can you tell me if you have a solution for that problem, I will do the same.

I found a solution

1st Step. Download Intel FPTW64 FPTW64 files I used from here and place all the files in your :\C folder. You will make a backup of your BIOS. To do this. Open CMD as Administrator then type cd C:\ then press Enter, then after that type.\fptw64.exe -bios -d bios_backup.bin . This will create a bios_backup.bin file which contains your bios password.

2nd Step. To decode the BIOS .bin file. You need HxD hex editor. Open your .bin file on the HxD program . This will show text you cannot undestand but you only need to use ctrl+f to find this specific location on the texts Use CTRL+F then go to the Hex-values tab and type this 00 65 00 72 00 76 00 69 00 73 00 6F 00 72 00 50. After that you will see on the left side under Decoded Text there is something like {S.y.s.t.e.m.S.u.p.e.r.v.i.s.o.r.P.w.....(this area will contain your password)aU?..........

Take a photo of that so you can type it when you log in to your BIOS .
--
  |

**Comment by okokokokokok94** [comment]
I used this  intel  fptw64 from badcaps forum [Intep FPTW64](https://www.badcaps.net/forum/attachment.php?attachmentid=244970&d=1632072808) 

And HxD hex editor [HxD Hex editor ](https://mh-nexus.de/en/hxd/)

**Comment by okokokokokok94** [comment]
This is the sample of the area in Hex editor location of the password 
![IMG_20211111_134702](https://user-images.githubusercontent.com/94042399/141394169-69cda331-735a-4c5c-a714-44bab2f0a65c.jpg)
My bios password is actually 147258 is located beside the S.u.p.e.r.v.i.s.o.r.P.w.....147258

**Comment by Cr0wTom** [comment]
Hello @okokokokokok94 ,

Thank you for your insights and for helping the community. Please consider making a commit describing in detail the process you mentioned in the proper place in this repo, and I'll try to approve it asap. I know it might be some work, but you might help a lot of people with the same issue in the future :)

I don't have the laptop anymore to test it so ut will be nice if someone else with the same issue proves it.

Thank you in advance.

**Comment by atsen-dev** [comment]
I'm testing now and it does not work, I launch in admin but I have an error when I want to dump...
![IMG_20211112_105320.jpg](https://user-images.githubusercontent.com/32575538/141447576-bb8259a0-28e3-4b97-b061-5edfe3ea3c61.jpg)
I have a mx250 version
Any idea?

**Comment by atsen-dev** [comment]
Hi, why this issue was closed ? THe issue always exists and the previous solution may not be the good solution for everyone.

My previous message wasn't answered and I'm always locked to acces my BIOS settings.

Thank in advance

**Comment by flgzzz** [comment]
> > Do you know why they doesn't want ? They doesn't also in a conversation not public ? Can you tell me if you have a solution for that problem, I will do the same.
> 
> I found a solution
> 
> 1st Step. Download Intel FPTW64 FPTW64 files I used from here and place all the files in your :\C folder. You will make a backup of your BIOS. To do this. Open CMD as Administrator then type cd C:\ then press Enter, then after that type.\fptw64.exe -bios -d bios_backup.bin . This will create a bios_backup.bin file which contains your bios password.
> 
> 2nd Step. To decode the BIOS .bin file. You need HxD hex editor. Open your .bin file on the HxD program . This will show text you cannot undestand but you only need to use ctrl+f to find this specific location on the texts Use CTRL+F then go to the Hex-values tab and type this 00 65 00 72 00 76 00 69 00 73 00 6F 00 72 00 50. After that you will see on the left side under Decoded Text there is something like {S.y.s.t.e.m.S.u.p.e.r.v.i.s.o.r.P.w.....(this area will contain your password)aU?..........
> 
> ## Take a photo of that so you can type it when you log in to your BIOS .
>   |

That worked for me, thanks a lot !! ❤️

**Comment by premjeetk4** [comment]
From Where I can download Intel FPTW64 file please give download link

**Comment by premjeetk4** [comment]
- not working 
- Error 2: Failure. Unexpected error occured
- mi notebook pro 14 8gb ram

**Comment by crutch12** [comment]
@okokokokokok94 God bless you

**Comment by Mofa2722** [comment]
> I found a solution
> 
> 1st Step. Download Intel FPTW64 FPTW64 files I used from here and place all the files in your :\C folder. You will make a backup of your BIOS. To do this. Open CMD as Administrator then type cd C:\ then press Enter, then after that type.\fptw64.exe -bios -d bios_backup.bin . This will create a bios_backup.bin file which contains your bios password.
> 
> 2nd Step. To decode the BIOS .bin file. You need HxD hex editor. Open your .bin file on the HxD program . This will show text you cannot undestand but you only need to use ctrl+f to find this specific location on the texts Use CTRL+F then go to the Hex-values tab and type this 00 65 00 72 00 76 00 69 00 73 00 6F 00 72 00 50. After that you will see on the left side under Decoded Text there is something like {S.y.s.t.e.m.S.u.p.e.r.v.i.s.o.r.P.w.....(this area will contain your password)aU?..........
> 
> ## Take a photo of that so you can type it when you log in to your BIOS .
>   |

I got my backup.bin file but i can't find the hex values. Also cant find any of the decoded text in search Ctrl+F. Here is a screenshot, my default language is german. But it says "could not find 00 65 00 72..." 
![test1](https://github.com/Cr0wTom/Mi-Notebook-Pro-Mods/assets/150487315/164a3859-99c1-4e09-966c-019635db9629)

**Comment by crutch12** [comment]
@Mofa2722 you should search in "Hex-values" tab.

Open Search window ang click "Hex-values" tab (the second one), then try to search.

**Comment by Mofa2722** [comment]
@crutch12 Ok thank you. I found the decoded text but it didnt worked. I tried System, SystemUserPw. I tried both german and english keyboard layout. Capital letters also seems not to be important. after 3 tries i have to restart the os.
![biospw](https://github.com/Cr0wTom/Mi-Notebook-Pro-Mods/assets/150487315/eaf66c45-6bcb-4ee6-86c3-9c1c3dadd3a2)

**Comment by 766F6964** [comment]
> @crutch12 Ok thank you. I found the decoded text but it didnt worked. I tried System, SystemUserPw. I tried both german and english keyboard layout. Capital letters also seems not to be important. after 3 tries i have to restart the os. ![biospw](https://private-user-images.githubusercontent.com/150487315/282265599-eaf66c45-6bcb-4ee6-86c3-9c1c3dadd3a2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM3OTE2MTksIm5iZiI6MTcxMzc5MTMxOSwicGF0aCI6Ii8xNTA0ODczMTUvMjgyMjY1NTk5LWVhZjY2YzQ1LTZiY2ItNGVlNi04NmMzLTljMWMzZGFkZDNhMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyMlQxMzA4MzlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05MGQ4Yzk1NTkwNjM1ZGE1MTJkNjUwZjJiODI5Zjg3MTE5ODFhYTMzNDY0MjIyZjIyNTI2MzM0OTRjMDczOTVmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.DbUErECMv-3ArOXhoUh7HvFUKsUhw6BSWiv9YWLTIUE)

Make sure to search for all occurrences. The string "SystemSupervisorPw" appears multiple times in the bios dump. One occurrence is followed by the password, while the others are blank, like the one shown in your screenshot.

**Comment by Deffuls** [comment]
It is closed, but i have not idea where to ask for help.
My laptop is RedmiBook Pro 16 2024, currently i have Ubuntu 24.04.

can someone help me ?

**Comment by Mofa2722** [comment]
> It is closed, but i have not idea where to ask for help. My laptop is RedmiBook Pro 16 2024, currently i have Ubuntu 24.04.
> 
> can someone help me ?

@Deffuls Did you try that ? 
 
> 1st Step. Download Intel FPTW64 FPTW64 files I used from here and place all the files in your :\C folder. You will make a backup of your BIOS. To do this. Open CMD as Administrator then type cd C:\ then press Enter, then after that type.\fptw64.exe -bios -d bios_backup.bin . This will create a bios_backup.bin file which contains your bios password.
> 
> 2nd Step. To decode the BIOS .bin file. You need HxD hex editor. Open your .bin file on the HxD program . This will show text you cannot undestand but you only need to use ctrl+f to find this specific location on the texts Use CTRL+F then go to the Hex-values tab and type this 00 65 00 72 00 76 00 69 00 73 00 6F 00 72 00 50. After that you will see on the left side under Decoded Text there is something like {S.y.s.t.e.m.S.u.p.e.r.v.i.s.o.r.P.w.....(this area will contain your password)aU?..........
>   |
> Make sure to search for all occurrences. The string "SystemSupervisorPw" appears multiple times in the bios dump. One occurrence is followed by the password, while the others are blank, like the one shown in your screenshot.

**Comment by Deffuls** [comment]
@Mofa2722 I can't do that. I am using now Ubuntu, so the only way i can run .exe is to run it under wine, but i get error.
"Unable to load PCI driver", i researched and i found that wine does not support such drivers.

Tomorrow i will try to run this using virtual box i hope this will work.

**Comment by vgrmdy** [comment]
### hello anybody,can someone helm me,please,has error when tried insert command to create BIOS dump.
![Screenshot_1](https://github.com/user-attachments/assets/3d8846cd-7adc-421e-aacd-3ae5d2964ec1)

```
C:\>.\fptw64.exe -bios -d bios_backup.bin

Intel (R) Flash Programming Tool. Version:  9.1.10.1000
Copyright (c) 2007 - 2014, Intel Corporation. All rights reserved.


Error 201: [FPTw64.exe] cannot be run on the current platform.
Please contact your vendor.
```

**Specs:**
_Xiaomi mi notebook pro 2018(i5,8gb,256gb)_

**Comment by ST1LLY** [comment]
Hello,
Having Mi Laptop Pro 15 2020 and trying to figure it out, I encountered such types of errors also:
```
Error 2: Failure. Unexpected error occurred
or 
Error 201: [FPTw64.exe] cannot be run on the current platform.
```

**General Approach**

You should use the appropriate version of FPTw64.exe to your bios version

**Guide**

Check the Intel ME Firmware Version in HWiNFO

1. Open HWiNFO64 (sensors or full mode).
2. On the left panel, expand the “Motherboard” or “Intel ME” section.
3. Look for something like:

```
Intel Management Engine
Firmware Version: 11.8.50.3425
```

In my case, it is Intel ME Version 14.0, Build 1125, Hot Fix 33
I used Intel CSME System Tools v14.0.20+ r20 with the following command to dump:
```
C:\>.\FPTW64.exe -bios -d dump_bios.in
```
Then opened dump_bios.in via HxD and search for the HEX-value: "00 65 00 72 00 76 00 69 00" to find the place

**Comment by Nick768** [comment]
Just for everybody who is searching for a solution that doesn't require Windows (or if the Windows approach doesn't work):
https://blog.nns.ee/2021/01/18/resetting-bios-password/

I was able to read my passwort but couldn't write to it or delete it.
