### ISSUE TITLE
UnderVolting in BIOS 906

### ISSUE THREAD

**Issue by MarFre22** [Cr0wTom/Mi-Notebook-Pro-Mods#7]
Hi Mi-Notebook-Pro-Mods community,

It's any possibility to have patches for BIOS 906? 
I think it is the best version we have (due to keyboard light and low noise of fans) and the undervolting patch will be great for hackintosh users for expand the battery time. 

Thank you very much community and a special thanks to the devs.

**Comment by vhladiienko** [comment]
You can use the existing voltage patch with 906. At least for me, it worked. I use ThrottleStop for UV, but XTU showed unlocked controls too.

**Comment by MarFre22** [comment]
Thanks, I will try.

**Comment by MarFre22** [comment]
I tried and it worked on BIOS 906.
Thanks for the help @vgladiyenko!!
