### ISSUE TITLE
Any tests done with Bios 805?

### ISSUE THREAD

**Issue by athuyaoo** [Cr0wTom/Mi-Notebook-Pro-Mods#8]
I am thinking of updating from 603 to 805 @Cr0wTom 

Thanks for your contributions!

**Comment by lowlevl** [comment]
Hello, I've updated to BIOS 906 and it's working great ! Tho the tutorial isn't precise enough for this version because the update process is a bit different..

**Comment by athuyaoo** [comment]
Any problems with the battery @Nurrl ? That's one of the drawbacks.

**Comment by Cr0wTom** [comment]
Hey guys. I haven't found the actual 805 BIOS for the MX model. It is only available for the GTX one. Also I have downgraded to 603 because the battery life in 906 was REALLY bad for me.

**Comment by lowlevl** [comment]
@travisryte, When I did sent the message I did just restarted from the update :)
So I don't know !
